import { Geist, Geist_Mono } from "next/font/google";
import './globals.css'      // 全体CSS
import Header from './components/Header'
import Footer from './components/Footer'

import { ClerkProvider } from "@clerk/nextjs";
import  ThemeCom from "./components/ThemeCom"
import { ThemeProvider } from "next-themes";
import{ThemeModeScript} from'flowbite-react';



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="ja" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <ThemeCom>
            <Header />
            {children}
            <Footer />
          </ThemeCom>
          </ThemeProvider>
      </body>
    </html>
    </ClerkProvider>
  );
}
